package server

import (
	"encoding/csv"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"

	"github.com/stockyard-dev/stockyard-booking/internal/store"
)

type Server struct {
	db      *store.DB
	mux     *http.ServeMux
	limits  Limits
	dataDir string
	pCfg    map[string]json.RawMessage // slug → personalization config
}

func New(db *store.DB, limits Limits, dataDir string) *Server {
	s := &Server{db: db, mux: http.NewServeMux(), limits: limits, dataDir: dataDir}
	s.loadPersonalConfig()
	s.mux.HandleFunc("GET /api/services", s.listServices)
	s.mux.HandleFunc("POST /api/services", s.createServices)
	s.mux.HandleFunc("GET /api/services/export.csv", s.exportServices)
	s.mux.HandleFunc("GET /api/services/{id}", s.getServices)
	s.mux.HandleFunc("PUT /api/services/{id}", s.updateServices)
	s.mux.HandleFunc("DELETE /api/services/{id}", s.delServices)
	s.mux.HandleFunc("GET /api/appointments", s.listAppointments)
	s.mux.HandleFunc("POST /api/appointments", s.createAppointments)
	s.mux.HandleFunc("GET /api/appointments/export.csv", s.exportAppointments)
	s.mux.HandleFunc("GET /api/appointments/{id}", s.getAppointments)
	s.mux.HandleFunc("PUT /api/appointments/{id}", s.updateAppointments)
	s.mux.HandleFunc("DELETE /api/appointments/{id}", s.delAppointments)
	s.mux.HandleFunc("GET /api/availability", s.listAvailability)
	s.mux.HandleFunc("POST /api/availability", s.createAvailability)
	s.mux.HandleFunc("GET /api/availability/export.csv", s.exportAvailability)
	s.mux.HandleFunc("GET /api/availability/{id}", s.getAvailability)
	s.mux.HandleFunc("PUT /api/availability/{id}", s.updateAvailability)
	s.mux.HandleFunc("DELETE /api/availability/{id}", s.delAvailability)
	s.mux.HandleFunc("GET /api/stats", s.stats)
	s.mux.HandleFunc("GET /api/health", s.health)
	s.mux.HandleFunc("GET /health", s.health)
	s.mux.HandleFunc("GET /ui", s.dashboard)
	s.mux.HandleFunc("GET /ui/", s.dashboard)
	s.mux.HandleFunc("GET /", s.root)
	s.mux.HandleFunc("GET /api/tier", s.tierHandler)
	s.mux.HandleFunc("GET /api/config", s.configHandler)
	s.mux.HandleFunc("GET /api/extras/{resource}", s.listExtras)
	s.mux.HandleFunc("GET /api/extras/{resource}/{id}", s.getExtras)
	s.mux.HandleFunc("PUT /api/extras/{resource}/{id}", s.putExtras)
	return s
}

// loadPersonalConfig reads config.json from the data directory.
// This file is generated by Stockyard's AI toolkit builder and contains
// personalization like dashboard title, custom fields, and placeholder names.
func (s *Server) loadPersonalConfig() {
	path := filepath.Join(s.dataDir, "config.json")
	data, err := os.ReadFile(path)
	if err != nil {
		return // no config file — use defaults, totally fine
	}
	var cfg map[string]json.RawMessage
	if err := json.Unmarshal(data, &cfg); err != nil {
		log.Printf("warning: could not parse config.json: %v", err)
		return
	}
	s.pCfg = cfg
	log.Printf("booking: loaded personalization from %s", path)
}

func (s *Server) configHandler(w http.ResponseWriter, r *http.Request) {
	if s.pCfg == nil {
		wj(w, 200, map[string]any{})
		return
	}
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(s.pCfg)
}

// listExtras returns all extras for a resource type as {record_id: {...fields...}}
func (s *Server) listExtras(w http.ResponseWriter, r *http.Request) {
	resource := r.PathValue("resource")
	all := s.db.AllExtras(resource)
	out := make(map[string]json.RawMessage, len(all))
	for id, data := range all {
		out[id] = json.RawMessage(data)
	}
	wj(w, 200, out)
}

// getExtras returns the extras blob for a single record.
func (s *Server) getExtras(w http.ResponseWriter, r *http.Request) {
	resource := r.PathValue("resource")
	id := r.PathValue("id")
	data := s.db.GetExtras(resource, id)
	w.Header().Set("Content-Type", "application/json")
	w.Write([]byte(data))
}

// putExtras stores the extras blob for a single record.
func (s *Server) putExtras(w http.ResponseWriter, r *http.Request) {
	resource := r.PathValue("resource")
	id := r.PathValue("id")
	body, err := io.ReadAll(r.Body)
	if err != nil {
		we(w, 400, "read body")
		return
	}
	// Validate it's JSON
	var probe map[string]any
	if err := json.Unmarshal(body, &probe); err != nil {
		we(w, 400, "invalid json")
		return
	}
	if err := s.db.SetExtras(resource, id, string(body)); err != nil {
		we(w, 500, "save failed")
		return
	}
	wj(w, 200, map[string]string{"ok": "saved"})
}

func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) { s.mux.ServeHTTP(w, r) }
func wj(w http.ResponseWriter, c int, v any) { w.Header().Set("Content-Type", "application/json"); w.WriteHeader(c); json.NewEncoder(w).Encode(v) }
func we(w http.ResponseWriter, c int, m string) { wj(w, c, map[string]string{"error": m}) }
func (s *Server) root(w http.ResponseWriter, r *http.Request) { if r.URL.Path != "/" { http.NotFound(w, r); return }; http.Redirect(w, r, "/ui", 302) }
func oe[T any](s []T) []T { if s == nil { return []T{} }; return s }
func init() { log.SetFlags(log.LstdFlags | log.Lshortfile) }

func (s *Server) listServices(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query().Get("q")
	filters := map[string]string{}
	if q != "" || len(filters) > 0 { wj(w, 200, map[string]any{"services": oe(s.db.SearchServices(q, filters))}); return }
	wj(w, 200, map[string]any{"services": oe(s.db.ListServices())})
}

func (s *Server) createServices(w http.ResponseWriter, r *http.Request) {
	if s.limits.Tier == "none" { we(w, 402, "No license key. Start a 14-day trial at https://stockyard.dev/for/"); return }
	if s.limits.TrialExpired { we(w, 402, "Trial expired. Subscribe at https://stockyard.dev/pricing/"); return }
	var e store.Services
	json.NewDecoder(r.Body).Decode(&e)
	if e.ServiceName == "" { we(w, 400, "service_name required"); return }
	s.db.CreateServices(&e)
	wj(w, 201, s.db.GetServices(e.ID))
}

func (s *Server) getServices(w http.ResponseWriter, r *http.Request) {
	e := s.db.GetServices(r.PathValue("id"))
	if e == nil { we(w, 404, "not found"); return }
	wj(w, 200, e)
}

func (s *Server) updateServices(w http.ResponseWriter, r *http.Request) {
	existing := s.db.GetServices(r.PathValue("id"))
	if existing == nil { we(w, 404, "not found"); return }
	var patch store.Services
	json.NewDecoder(r.Body).Decode(&patch)
	patch.ID = existing.ID; patch.CreatedAt = existing.CreatedAt
	if patch.ServiceName == "" { patch.ServiceName = existing.ServiceName }
	if patch.Description == "" { patch.Description = existing.Description }
	s.db.UpdateServices(&patch)
	wj(w, 200, s.db.GetServices(patch.ID))
}

func (s *Server) delServices(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id"); s.db.DeleteServices(id); s.db.DeleteExtras("services", id)
	wj(w, 200, map[string]string{"deleted": "ok"})
}

func (s *Server) exportServices(w http.ResponseWriter, r *http.Request) {
	items := s.db.ListServices()
	w.Header().Set("Content-Type", "text/csv")
	w.Header().Set("Content-Disposition", "attachment; filename=services.csv")
	cw := csv.NewWriter(w)
	cw.Write([]string{"id", "service_name", "duration_minutes", "price", "description", "active", "created_at"})
	for _, e := range items {
		cw.Write([]string{e.ID, fmt.Sprintf("%v", e.ServiceName), fmt.Sprintf("%v", e.DurationMinutes), fmt.Sprintf("%v", e.Price), fmt.Sprintf("%v", e.Description), fmt.Sprintf("%v", e.Active), e.CreatedAt})
	}
	cw.Flush()
}

func (s *Server) listAppointments(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query().Get("q")
	filters := map[string]string{}
	if v := r.URL.Query().Get("status"); v != "" { filters["status"] = v }
	if q != "" || len(filters) > 0 { wj(w, 200, map[string]any{"appointments": oe(s.db.SearchAppointments(q, filters))}); return }
	wj(w, 200, map[string]any{"appointments": oe(s.db.ListAppointments())})
}

func (s *Server) createAppointments(w http.ResponseWriter, r *http.Request) {
	var e store.Appointments
	json.NewDecoder(r.Body).Decode(&e)
	if e.ClientName == "" { we(w, 400, "client_name required"); return }
	if e.Date == "" { we(w, 400, "date required"); return }
	if e.Time == "" { we(w, 400, "time required"); return }
	s.db.CreateAppointments(&e)
	wj(w, 201, s.db.GetAppointments(e.ID))
}

func (s *Server) getAppointments(w http.ResponseWriter, r *http.Request) {
	e := s.db.GetAppointments(r.PathValue("id"))
	if e == nil { we(w, 404, "not found"); return }
	wj(w, 200, e)
}

func (s *Server) updateAppointments(w http.ResponseWriter, r *http.Request) {
	existing := s.db.GetAppointments(r.PathValue("id"))
	if existing == nil { we(w, 404, "not found"); return }
	var patch store.Appointments
	json.NewDecoder(r.Body).Decode(&patch)
	patch.ID = existing.ID; patch.CreatedAt = existing.CreatedAt
	if patch.ClientName == "" { patch.ClientName = existing.ClientName }
	if patch.ClientEmail == "" { patch.ClientEmail = existing.ClientEmail }
	if patch.ClientPhone == "" { patch.ClientPhone = existing.ClientPhone }
	if patch.Service == "" { patch.Service = existing.Service }
	if patch.Date == "" { patch.Date = existing.Date }
	if patch.Time == "" { patch.Time = existing.Time }
	if patch.Status == "" { patch.Status = existing.Status }
	if patch.Notes == "" { patch.Notes = existing.Notes }
	s.db.UpdateAppointments(&patch)
	wj(w, 200, s.db.GetAppointments(patch.ID))
}

func (s *Server) delAppointments(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id"); s.db.DeleteAppointments(id); s.db.DeleteExtras("appointments", id)
	wj(w, 200, map[string]string{"deleted": "ok"})
}

func (s *Server) exportAppointments(w http.ResponseWriter, r *http.Request) {
	items := s.db.ListAppointments()
	w.Header().Set("Content-Type", "text/csv")
	w.Header().Set("Content-Disposition", "attachment; filename=appointments.csv")
	cw := csv.NewWriter(w)
	cw.Write([]string{"id", "client_name", "client_email", "client_phone", "service", "date", "time", "status", "notes", "created_at"})
	for _, e := range items {
		cw.Write([]string{e.ID, fmt.Sprintf("%v", e.ClientName), fmt.Sprintf("%v", e.ClientEmail), fmt.Sprintf("%v", e.ClientPhone), fmt.Sprintf("%v", e.Service), fmt.Sprintf("%v", e.Date), fmt.Sprintf("%v", e.Time), fmt.Sprintf("%v", e.Status), fmt.Sprintf("%v", e.Notes), e.CreatedAt})
	}
	cw.Flush()
}

func (s *Server) listAvailability(w http.ResponseWriter, r *http.Request) {
	q := r.URL.Query().Get("q")
	filters := map[string]string{}
	if v := r.URL.Query().Get("day_of_week"); v != "" { filters["day_of_week"] = v }
	if q != "" || len(filters) > 0 { wj(w, 200, map[string]any{"availability": oe(s.db.SearchAvailability(q, filters))}); return }
	wj(w, 200, map[string]any{"availability": oe(s.db.ListAvailability())})
}

func (s *Server) createAvailability(w http.ResponseWriter, r *http.Request) {
	var e store.Availability
	json.NewDecoder(r.Body).Decode(&e)
	if e.DayOfWeek == "" { we(w, 400, "day_of_week required"); return }
	if e.StartTime == "" { we(w, 400, "start_time required"); return }
	if e.EndTime == "" { we(w, 400, "end_time required"); return }
	s.db.CreateAvailability(&e)
	wj(w, 201, s.db.GetAvailability(e.ID))
}

func (s *Server) getAvailability(w http.ResponseWriter, r *http.Request) {
	e := s.db.GetAvailability(r.PathValue("id"))
	if e == nil { we(w, 404, "not found"); return }
	wj(w, 200, e)
}

func (s *Server) updateAvailability(w http.ResponseWriter, r *http.Request) {
	existing := s.db.GetAvailability(r.PathValue("id"))
	if existing == nil { we(w, 404, "not found"); return }
	var patch store.Availability
	json.NewDecoder(r.Body).Decode(&patch)
	patch.ID = existing.ID; patch.CreatedAt = existing.CreatedAt
	if patch.DayOfWeek == "" { patch.DayOfWeek = existing.DayOfWeek }
	if patch.StartTime == "" { patch.StartTime = existing.StartTime }
	if patch.EndTime == "" { patch.EndTime = existing.EndTime }
	s.db.UpdateAvailability(&patch)
	wj(w, 200, s.db.GetAvailability(patch.ID))
}

func (s *Server) delAvailability(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id"); s.db.DeleteAvailability(id); s.db.DeleteExtras("availability", id)
	wj(w, 200, map[string]string{"deleted": "ok"})
}

func (s *Server) exportAvailability(w http.ResponseWriter, r *http.Request) {
	items := s.db.ListAvailability()
	w.Header().Set("Content-Type", "text/csv")
	w.Header().Set("Content-Disposition", "attachment; filename=availability.csv")
	cw := csv.NewWriter(w)
	cw.Write([]string{"id", "day_of_week", "start_time", "end_time", "active", "created_at"})
	for _, e := range items {
		cw.Write([]string{e.ID, fmt.Sprintf("%v", e.DayOfWeek), fmt.Sprintf("%v", e.StartTime), fmt.Sprintf("%v", e.EndTime), fmt.Sprintf("%v", e.Active), e.CreatedAt})
	}
	cw.Flush()
}

func (s *Server) stats(w http.ResponseWriter, r *http.Request) {
	m := map[string]any{}
	m["services_total"] = s.db.CountServices()
	m["appointments_total"] = s.db.CountAppointments()
	m["availability_total"] = s.db.CountAvailability()
	wj(w, 200, m)
}

func (s *Server) health(w http.ResponseWriter, r *http.Request) {
	m := map[string]any{"status": "ok", "service": "booking"}
	m["services"] = s.db.CountServices()
	m["appointments"] = s.db.CountAppointments()
	m["availability"] = s.db.CountAvailability()
	wj(w, 200, m)
}
